name = "vinhack2026"
main = "./.vercel/output/functions/entry.mjs"
account_id = "5a758751b5a509eef4a1482ae4492d39"
compatibility_date = "2025-08-07"

[assets]
directory = "./.vercel/output/static"
binding = "ASSETS"

# KV namespace for Next.js cache
# Create this first: npx wrangler kv namespace create NEXT_CACHE
# Then replace the id and preview_id values below
# [[kv_namespaces]]
# binding = "NEXT_CACHE"
# id = ""
# preview_id = ""
