/**
 * Curated list of 750+ funny, clever, tech-themed hackathon team names.
 * Covers programming puns, AI/ML memes, developer culture, late-night hackathon hustle,
 * cybersecurity, hardware, algorithms, and nerdy pop culture.
 */

export const HACKATHON_TEAM_NAMES: readonly string[] = [
  // --- Programming Puns & Syntax Chaos ---
  "404 Brain Not Found",
  "Null Pointers",
  "Ctrl Alt Defeat",
  "Byte Me",
  "Git Committed",
  "Recursion Rejects",
  "Stack Overflowers",
  "Syntax Terrors",
  "Kernel Panic",
  "Segfault Sorcerers",
  "Infinite Loops",
  "Bug Busters",
  "Rubber Duckies",
  "Cache Me If You Can",
  "Merge Conflict Survivors",
  "Caffeine Overdrive",
  "Drop Table Teams",
  "Sudo Make Sandwich",
  "Spaghetti Coders",
  "Bits Please",
  "The Algorhythmics",
  "Commit or Die",
  "Binary Beasts",
  "OutOfMemory",
  "While(1) Sleep(0)",
  "Runtime Terrors",
  "Boolean Babes",
  "Promise Kept",
  "Async Awaiters",
  "Terminal Velocity",
  "Git Rebase & Cry",
  "Curly Bracket Clan",
  "Undefined Behaviour",
  "Off By One",
  "Semicolon Slashers",
  "Code Blooded",
  "Exception Handlers",
  "Type Errors Anonymous",
  "Garbage Collectors",
  "Dangling Pointers",
  "Heap Overflow",
  "Zero Day Zeros",
  "Race Conditioners",
  "Deadlock Detectors",
  "Bit Shifters",
  "Logic Bombers",
  "Variable Vandals",
  "Constant Chaos",
  "Array Index Out Of Bounds",
  "Stack Tracers",
  "Memory Leakers",
  "Buffer Bandits",
  "Big-O No No",
  "Recursion Recursion Recursion",
  "Base Case Breakers",
  "Tail Call Optimizers",
  "Monad Monsters",
  "Lambda Lords",
  "Closure Creators",
  "Immutable Morons",
  "Pure Functions Only",
  "Side Effect Saboteurs",
  "State Mutators",
  "Callback Hell Divers",
  "Event Loop Evaders",
  "Promise Rejected",
  "Fetch Failures",
  "Payload Pirates",
  "Query Killers",
  "Schema Smashers",
  "Relational Rejects",
  "NoSQL NoProblems",
  "Foreign Key Fugitives",
  "Primary Key Perps",
  "Index Ignorers",
  "Full Table Scanners",
  "Lock Wait Timeouts",
  "Transaction Rollbacks",
  "Acid Reflux",
  "Normalization Nazis",
  "Denormalized Disasters",
  "JSON Jesters",
  "YAML Yodellers",
  "XML Xterminators",
  "Regex Regret",
  "Greedy Quantifiers",
  "Lookahead Lunatics",
  "Lookbehind Bandits",
  "Escape Sequence Escapists",
  "Wildcard Warriors",
  "Pipe dreamers",
  "Grep Groovy",
  "Awkward Awk",
  "Sed And Breakfast",
  "Bash Brothers",
  "Zsh Zealots",
  "Fish Out Of Water",
  "PowerShell Powerhouses",
  "Batch File Bullies",
  "Cron Job Clowns",
  "Daemon Demolishers",
  "Process Killers",
  "Fork Bombers",
  "Zombie Processors",
  "Orphan Reapers",
  "Init Invalids",
  "Systemd Sufferers",
  "Root Cause Seekers",
  "Permission Denied",
  "Chmod 777 Enthusiasts",
  "Chown Clowns",
  "Symlink Stumblers",
  "Hard Link Heroes",
  "Inode Intruders",
  "File Descriptor Fanatics",

  // --- AI, ML & Data Science Shenanigans ---
  "Overfitted Overlords",
  "Gradient Descenters",
  "Loss Function Losers",
  "Epoch Fails",
  "Hallucination Nation",
  "Prompt Engineers Anonymous",
  "Neural Net Worth",
  "Token Bandits",
  "Attention Is All You Need",
  "Transformer Terrors",
  "Zero Shot Heroes",
  "Few Shot Fighters",
  "Backprop Bandits",
  "Convolutional Chaos",
  "TensorFlow Tourists",
  "PyTorch Pyros",
  "Scikit Scoundrels",
  "NumPy Ninjas",
  "Pandas In Pajamas",
  "Jupyter Astronauts",
  "Data Wrangling Wranglers",
  "Feature Creepers",
  "Dimension Reducers",
  "Eigenvector Evaders",
  "Latent Space Cadets",
  "Embedding Embedders",
  "Vector Database Vultures",
  "Cosine Similarity Clones",
  "RAG Tag Fleet",
  "Fine Tuning Fanatics",
  "Context Window Cleaners",
  "Temperature 1.0 Wildcards",
  "Top-P Pirates",
  "Reinforcement Rebels",
  "Markov Chainsaws",
  "Stochastic Parrots",
  "Bayesian Bandits",
  "Random Forest Rangers",
  "Decision Tree Huggers",
  "XGBoost Xtreme",
  "K-Means Klowns",
  "Support Vector Mutants",
  "Sigmoid Sizzlers",
  "Softmax Snipers",
  "ReLU Rascals",
  "Vanishing Gradients",
  "Exploding Gradients",
  "Learning Rate Lemmings",
  "Batch Norm Bandits",
  "Dropout Dropouts",
  "Cross Entropy Crusaders",
  "Mean Squared Errors",
  "Confusion Matrix Misfits",
  "Precision Recall Punks",
  "ROC Curve Rollers",
  "Underfitted Underdogs",
  "Model Drift Drifters",
  "Data Leakage Plumbers",
  "Overparameterized",
  "AGI When?",
  "Turing Test Traitors",
  "Perceptron Posse",
  "Autoencoder Architects",
  "Diffusion Delinquents",
  "Latent Diffusion Lunatics",
  "LoRA Lovers",
  "Quantized Quandaries",
  "Weights And Biases Bribers",
  "Hyperparameter Hackers",
  "Grid Search Gladiators",
  "Curse Of Dimensionality",
  "Synthetic Data Sellers",
  "Ground Truth Deniers",
  "P-Value Hackers",
  "Correlation Not Causation",
  "Standard Deviation Deviants",
  "Outlier Outlaws",
  "Gaussian Gang",

  // --- Web Dev, CSS & Frontend Quirks ---
  "CSS Is Awesome",
  "Flexbox Flexers",
  "Grid Goblins",
  "Z-Index 999999",
  "CORS Victims",
  "Cookie Monsters",
  "LocalStorage Hoarders",
  "Session Hijackers",
  "DOM Terminators",
  "Virtual DOM Virtuosos",
  "Shadow DOM Shady",
  "Hydration Errors",
  "Re-render Riot",
  "Prop Drillers",
  "State Management Sufferers",
  "Redux Regret",
  "Zustand Zealots",
  "Jotai Jockeys",
  "Context Clowns",
  "Hooked On A Feeling",
  "useEffect Infinite Loop",
  "useMemo Forgetters",
  "useCallback Confused",
  "NextJS Nuances",
  "Turbopack Turbos",
  "Webpack Wasters",
  "Vite Lightning",
  "Rollup Rollers",
  "Babel Babblers",
  "Tailwind Fanatics",
  "Inline Style Sinners",
  "Important! Rebels",
  "Centering Div Sorcerers",
  "Margin Auto Magicians",
  "Padding Panic",
  "Box-Sizing Border-Box",
  "Overflow Hidden Outlaws",
  "Float Clearers",
  "Sticky Nav Nightmares",
  "Parallax Paralyzers",
  "Scroll Jackers",
  "Viewport Vipers",
  "Media Query Mediators",
  "Responsive Responders",
  "Mobile First Monsters",
  "Lighthouse Score 100",
  "FOUC Fighters",
  "Asset Optimizers",
  "Favicon Forgetting",
  "Dark Mode Only",
  "Glassmorphism Geeks",
  "Neumorphism Nostalgia",
  "Skeuomorphic Skeletons",
  "Pixel Pushers",
  "Kerning Killers",
  "Comic Sans Criminals",
  "WebAssembly Wizards",
  "Canvas Crawlers",
  "WebGL Warriors",
  "ThreeJS Thrillers",
  "Service Worker Strikers",
  "PWA Paladins",
  "Brotli Bandits",
  "Gzip Gremlins",
  "Cache Busting Busters",
  "ETag Enthusiasts",
  "CORS Preflight Pilots",
  "Status 418 Teapots",
  "Status 200 But Actually 500",
  "Redirect Loopers",
  "Mixed Content Mavericks",
  "Cert Bot Champions",

  // --- Late-Night Hackathon Hustle & Caffeine ---
  "Red Bull Run Club",
  "3 AM Commit Club",
  "Monsters & Red Bulls",
  "Sleep Is For Release Branch",
  "Hack To The Future",
  "Works On My Machine",
  "Production Testers",
  "Debugging In Production",
  "Ship It Squirrels",
  "Slide Deck Magicians",
  "Pitch Deck Hustlers",
  "Demo Gods Praying",
  "Live Demo Disasters",
  "Vaporware Visions",
  "Fake It Till You Make It",
  "MVP Most Vulnerable Product",
  "Coffee To Code Converters",
  "Pizza Crust Crew",
  "Monster Energy Mutants",
  "Cold Brew Cartel",
  "Espresso Express",
  "Caffeine Synthesizers",
  "All Nighter Nomads",
  "Dawn Patrol Pushers",
  "Last Minute Refactorers",
  "Pre-pitch Panic",
  "Presentation Panic",
  "Figma To Code In 10 Mins",
  "Canva Conquerors",
  "Readme Writers Guild",
  "Sponsor Swag Collectors",
  "Free Pizza Connoisseurs",
  "Snack Table Snipers",
  "Hackathon Hoppers",
  "Judging Table Jitters",
  "Two Minutes Left",
  "Git Push --Force And Pray",
  "Keyboard Smashes",
  "Wired On Wi-Fi",
  "Venue Floor Campers",
  "Power Strip Bandits",
  "Extension Cord Empire",
  "Dongle Danglers",
  "Laptop Battery At 1%",
  "Charger Chasers",
  "Hotspot Heroes",
  "Offline Coders",
  "Git Blame Somebody Else",
  "Merge Conflicts At 2:59",
  "Commented Out Production",
  "Console Log Detectives",
  "Alert Box Debuggers",
  "Todo: Fix Later",
  "Fix Later Never Comes",
  "Hackathon Royalty",
  "Speedrunners Of Software",
  "Sprint To Nowhere",
  "Scrum And Coke",
  "Agile Agony",
  "Standup Sitdowns",
  "Burndown Burnouts",
  "Technical Debt Millionaires",
  "Code Debt Collectors",
  "Quick And Dirty",
  "Spaghetti And Meatballs",
  "Tape And Bubblegum",
  "Held By Band-Aids",
  "Works 60% Of The Time",
  "Flawless First Try",
  "No Unit Tests No Problems",
  "Tests In Production",
  "QA? What QA?",

  // --- Cloud, DevOps & Infrastructure ---
  "Kubernetes Cowboys",
  "Docker Dwellers",
  "Container Containment",
  "Microservice Monoliths",
  "Distributed Dilemmas",
  "Serverless Server Seekers",
  "Lambda Leapfrogs",
  "Cloudflare Tunnel Rats",
  "AWS Bill Shockers",
  "GCP Grant Grabbers",
  "Azure Anguish",
  "Terraform Terrors",
  "Ansible Anarchists",
  "Puppet Masters",
  "Vagrant Vagabonds",
  "YAML Whisperers",
  "Helm Chart Cartographers",
  "Ingress Infiltrators",
  "Egress Escapists",
  "Load Balancer Jugglers",
  "Reverse Proxy Posse",
  "Nginx Knights",
  "Traefik Traffic",
  "Caddy Caddies",
  "Zero Downtime Dreamers",
  "Blue-Green Gamblers",
  "Canary In The Coal Mine",
  "Rolling Update Roadkill",
  "Cold Boot Sufferers",
  "Edge Function Fanatics",
  "Origin Shield Shakers",
  "S3 Bucket Leakers",
  "CloudFront Clowns",
  "VPC Vanishers",
  "Subnet Surfers",
  "CIDR Block Blockers",
  "NAT Gateway Bankrupts",
  "Auto Scalers Gone Wild",
  "Cluster Crashers",
  "Pod Eviction Victims",
  "OOMKilled Soldiers",
  "CrashLoopBackOff Crew",
  "Readiness Probe Rejectors",
  "Liveness Probe Laggards",
  "Sidecar Stowaways",
  "Service Mesh Mayhem",
  "Istio Invalids",
  "Kafka Chaos",
  "RabbitMQ Runaways",
  "Event Driven Druids",
  "PubSub Punishers",
  "Message Queue Misery",
  "Dead Letter Dropouts",
  "Grafana Graphomaniacs",
  "Prometheus Pyros",
  "Datadog Daycare",
  "Sentry Sentrymen",
  "Log Aggregator Overflows",
  "Alert Fatigue Fighters",
  "On-Call Catastrophes",
  "Incident Responders",
  "Post-Mortem Party",
  "Five Whys Waiters",

  // --- Cybersecurity, Hacking & Exploits ---
  "SQL Injections",
  "Cross-Site Scripting",
  "Zero Day Explorers",
  "White Hat Wizards",
  "Black Hat Bandits",
  "Grey Hat Gamblers",
  "Packet Sniffers",
  "Script Kiddies",
  "Buffer Overflowers",
  "Payload Pushers",
  "Penetration Testers",
  "Brute Force Bruisers",
  "Hash Crackers",
  "Rainbow Table Rollers",
  "Salting And Hashing",
  "Bcrypt Barons",
  "Man In The Middle",
  "Phishing Rods",
  "Spear Phishing Sharks",
  "Social Engineers",
  "DDoS Dynamo",
  "Botnet Bosses",
  "Trojan Horses",
  "Worm Wranglers",
  "Ransomware Removers",
  "Reverse Engineers",
  "Disassembler Demons",
  "Decompiler Detectives",
  "Ghidra Guild",
  "IDA Pro Posse",
  "Wireshark Wonders",
  "Nmap Navigators",
  "Metasploit Mercenaries",
  "Burp Suite Bards",
  "Honeypot Harvesters",
  "Firewall Fighters",
  "Air-Gapped Astronauts",
  "Privilege Escalators",
  "Kernel Exploiters",
  "Rootkit Rangers",
  "Shellcode Scribes",
  "Keylogger Killers",
  "Cipher Chasers",
  "RSA Rebels",
  "Elliptic Curve Enthusiasts",
  "Diffie-Hellman Devils",
  "One-Time Padded",
  "Quantum Decryptors",
  "Entropy Exceeders",
  "Zero Knowledge Proofers",
  "Shamir Secret Sharers",
  "Bounty Hunters",
  "Hall Of Famers",
  "CVE Collectors",
  "Exploit Developers",
  "Sandboxed Saboteurs",

  // --- Hardware, IoT & Embedded Lunacy ---
  "Thermal Throttled",
  "Blue Screen Of Death",
  "Overclocked Overthinkers",
  "Silicon Valley Of Tears",
  "Clock Speed Demons",
  "Solder Sniffers",
  "Magic Blue Smoke",
  "Fried Capacitors",
  "Resistor Rebels",
  "Breadboard Brawlers",
  "Jumper Wire Jungle",
  "Arduino Astronauts",
  "Raspberry Pi Pirates",
  "ESP32 Evaders",
  "GPIO Gang",
  "I2C Interrupters",
  "SPI Spies",
  "UART Utopians",
  "Baud Rate Bandits",
  "Blinking LEDs Forever",
  "Firmware Fryers",
  "Bootloader Busters",
  "Flash Memory Flunkies",
  "EEPROM Erasers",
  "Oscilloscope Operators",
  "Logic Analyzer Looneys",
  "Soldering Iron Burns",
  "Flux Capacitors",
  "PCB Pathfinders",
  "Via Violators",
  "Trace Route Trackers",
  "Ground Loop Gremlins",
  "Noisy ADC Nomads",
  "PWM Modulators",
  "Microcontroller Mavericks",
  "ARM Architecture Army",
  "RISC-V Vanguard",
  "x86 Dinosaurs",
  "Transistor Tyrants",
  "Silicon Wafers",
  "Die Shrink Shrinks",
  "Moore's Law Outlaws",
  "Fan Noise 100%",
  "Liquid Cooled Lunatics",
  "Heatsink Hustlers",
  "Thermal Paste Picasso",
  "Voltage Regulators",
  "Current Surfers",
  "Ohm's Law Breakers",

  // --- Nerdy Pop Culture, Sci-Fi & Gamer Puns ---
  "The Lord Of The Pings",
  "Game Of Throws",
  "Doctor Whoami",
  "Stranger Pings",
  "Breaking Binary",
  "Silicon Knights",
  "The Matrix Reloaded (npm)",
  "Avengers: Endian",
  "Star Wars: Return of the Jedi(Object)",
  "The Big Bang Operator",
  "Hitchhiker's Guide To The Cluster",
  "2001: A Code Odyssey",
  "Mad Max: Fury Road To Prod",
  "Jurassic Parked Threads",
  "The Shawshank Redirection",
  "Pulp Function",
  "Fight Club: Rule 1 No Push On Friday",
  "Inception: A Function Within A Function",
  "Back To The Git Feature",
  "Blade Runners On Linux",
  "Terminator: Judgment Day (Release)",
  "Indiana Jones And The Temple Of Doom(Loop)",
  "Pirates Of The Silicon",
  "Harry Potter And The Order Of Execution",
  "Fantastic Beasts And Where To Host Them",
  "Lord Of The Ring Buffers",
  "Fellowship Of The Ping",
  "Two Towers: Client & Server",
  "Return Of The King Of Algorithms",
  "A Game Of Nodes",
  "Winter Is Coming: Code Freeze",
  "House of Targaryen(Tag)",
  "Breaking Bad Code",
  "Better Call Sudo",
  "Stranger Strings",
  "The IT Crowd Survivors",
  "Have You Tried Turning It Off And On?",
  "Moss And Roy",
  "Silicon Valley Aviato",
  "Pied Piper Middle Out",
  "Not Hotdog Hackers",
  "Gilfoyle's Daemons",
  "Dinesh's Disasters",
  "Mr. Robot Wannabes",
  "fsociety Outcasts",
  "Dark Army Devs",
  "Cyberpunk 2077 Bugs",
  "Skyrim Stepping On Buckets",
  "Portal: The Cake Is A Lie",
  "Half-Life 3 Confirmed (On Branch)",
  "Dark Souls: You Died (In Prod)",
  "Minecraft Redstone Engineers",
  "Roblox Revolutionaries",
  "Among Us Impostor Commits",
  "Grand Theft Auto: San Andreas (Git)",
  "Call of Duty: Modern Bugfare",
  "Fallout: New Vegas Deploy",
  "Zelda: Breath Of The Wildcard",
  "Super Mario Bros (Brokers)",
  "Pokémon: Gotta Catch All Exceptions",
  "Pikachu Thunder-Patch",
  "Charizard Cache Burner",

  // --- Witty Wordsmiths & Quirky Clever Concepts ---
  "Bits & Pieces",
  "Code & Coffee",
  "Ctrl Freak",
  "Data Day Saints",
  "Debug Thugs",
  "Devils In The Details",
  "Digital Nomads",
  "Drink Tea Make PR",
  "Dynamic Dynamos",
  "Errorist Cell",
  "Fast & Curious",
  "Fatal Attraction to Code",
  "Feature Not A Bug",
  "First Class Functions",
  "Full Stack Panic",
  "Get Rich Or Die Coding",
  "Git R Done",
  "Gold Miners of Silicon",
  "Hack Attack",
  "Hacking Bad",
  "Headless Horsemen",
  "Hex Appeal",
  "Holy Sheet",
  "Hopeless Romantic Coders",
  "Hotfix Heroes",
  "Hub & Spoke Mob",
  "Insert Coin To Continue",
  "It Compiles On My Machine",
  "It Was Working Yesterday",
  "Java The Hutt",
  "Just In Time Compilers",
  "Knights of the Round Array",
  "Lazy Evaluators",
  "Look Ma No Hands",
  "Lost In Space Complexity",
  "Mad Catz Controller",
  "Master Branch Masters",
  "Meaning Of Life Is 42",
  "Mind Over Middleware",
  "Misery Loves Company (Agile)",
  "Monolith Monsters",
  "Naively Bayes",
  "Natural Born Coders",
  "Nerds of the Round Table",
  "Newbie Nibbles",
  "No Comment Given",
  "No Pressure Just Prod",
  "No Sarcasm In Code",
  "No Sleep Till Sunday",
  "Not Today Murphy's Law",
  "Null And Void",
  "One Byte At A Time",
  "One Line Wonders",
  "Only Fans Of Linux",
  "Oops I Did It Again (Drop DB)",
  "Optimize Prematurely",
  "Origin Main Or Bust",
  "Packets On The Loose",
  "Panic At The Distro",
  "Peanut Butter & Jellyfish",
  "Periodic Table Of Elements",
  "Persistence Pays Off",
  "Ping Of Death",
  "Pixel Perfectionists",
  "Plain Text Purists",
  "Please Stand By",
  "Polymorphic Polymaths",
  "Pop The Stack",
  "Pre-alpha Predators",
  "Programmer's Block",
  "Proof Of Concept",
  "Prototypical Inheritance",
  "Push To Master Friday 5PM",
  "Quirky Quarks",
  "Rapid Prototypers",
  "Raw Dogging Production",
  "Reboot And Pray",
  "Red Screen Of Screaming",
  "Refactor In Peace",
  "Release The Kraken",
  "Remote Control Freaks",
  "Rest In Peace CPU",
  "Return Null",
  "Road To 100k Lines",
  "Rubik's Coders",
  "Salty Bytes",
  "Scraping The Web",
  "Screen Staring Champions",
  "Script Surgeons",
  "Seamless Integration (Lie)",
  "Search Engine Optimists",
  "Second Place Is First Loser",
  "Semantic Versioners",
  "Semi-Autonomous Sloths",
  "Serial Killers (Comm Port)",
  "Server Huggers",
  "Ship First Ask Questions Later",
  "Shortcut Junkies",
  "Silicon Savants",
  "Single Point Of Failure",
  "Sink Or Swim In C",
  "Sleep Deprivation Station",
  "Sloth Speed Sorting",
  "Smart Pointer Snobs",
  "Snack Driven Development",
  "Socially Awkward Geeks",
  "Software Chameleons",
  "Something Went Wrong",
  "Source Code Sorcery",
  "Speedy Gonzales",
  "Spill The Tea (API)",
  "Stack Traced",
  "Static Shockers",
  "Stay Grounded",
  "Stolen From StackOverflow",
  "Structured Chaos",
  "Style Over Substance",
  "Super User Doers",
  "System Failure",
  "Table Scraps",
  "Taking The Byte Out Of Crime",
  "Target Audience: Nobody",
  "Team Alpha",
  "Team Broke The Build",
  "Team Caffeine",
  "Team Chaos",
  "Team Ctrl+Z",
  "Team Does Not Exist",
  "Team Eleven",
  "Team Free Food",
  "Team Git Revert",
  "Team Glitch",
  "Team Infinite Loop",
  "Team Last Minute",
  "Team Name Not Found",
  "Team No Sleep",
  "Team Null",
  "Team Open Source",
  "Team Overclock",
  "Team Panic",
  "Team Red Bull",
  "Team Reloaded",
  "Team Semicolon",
  "Team Sudo",
  "Team TBD",
  "Team Underdog",
  "Team Untitled",
  "Team Victory",
  "Team Whoami",
  "Tech Debt Millionaires",
  "The Abstract Factories",
  "The Agile Addicts",
  "The Binary Bandits",
  "The Bit Flippers",
  "The Block Blockers",
  "The Boolean Brigades",
  "The Bootleg Hackers",
  "The Bug Finders",
  "The Bug Keepers",
  "The Byte Brawlers",
  "The Code Crushers",
  "The Code Ninjas",
  "The Code Wizards",
  "The Compiler Compilers",
  "The Cookie Clickers",
  "The Crashing Kernels",
  "The Curly Braces",
  "The Daily Standdowns",
  "The Dangling Nodes",
  "The Dark Mode Devs",
  "The Data Miners",
  "The Deadlockers",
  "The Debuggers",
  "The Default Gateways",
  "The Dev Ops",
  "The Dirty Bits",
  "The Disrupters",
  "The Docker Dudes",
  "The Dynamic Duos",
  "The Edge Cases",
  "The Elves of Silicon",
  "The Error Loggers",
  "The Escape Artists",
  "The Executioners",
  "The Final Commits",
  "The Flawless Founders",
  "The Framework Fumble",
  "The Frontend Phenoms",
  "The Full Stacks",
  "The Function Function",
  "The Fuzzy Logicians",
  "The Garbage Collectors",
  "The Ghost In The Machine",
  "The Git Pushes",
  "The Global Variables",
  "The Google Searchers",
  "The GPU Melters",
  "The Hacker Clan",
  "The Hardcoded Heroes",
  "The Hash Maps",
  "The Hexadecimal Hooligans",
  "The High Pings",
  "The Hit And Runs",
  "The Hotkey Hackers",
  "The Idle Tasks",
  "The Inlines",
  "The Instant Ramen Crew",
  "The Integer Overflows",
  "The Interface Interpreters",
  "The JIT Junkies",
  "The Keyboard Warriors",
  "The Late Night Coders",
  "The Leaky Abstractions",
  "The Legacy Maintainers",
  "The Linear Searchers",
  "The Little Endians",
  "The Localhosts",
  "The Logic Gates",
  "The Magic Numbers",
  "The Mainframes",
  "The Memory Dumps",
  "The Microservices",
  "The Midnight Oil",
  "The Modular Mavericks",
  "The Monads",
  "The Monolithic Crew",
  "The Mutable States",
  "The Nanoseconds",
  "The Network Nerds",
  "The Next Big Thing",
  "The Noobs",
  "The Null Values",
  "The Number Crunchers",
  "The Octal Overlords",
  "The One Time Only",
  "The Open Sourced",
  "The Operating Systems",
  "The Out Of Memorys",
  "The Overachievers",
  "The Overloaded Operators",
  "The Packet Loss Posse",
  "The Patch Work",
  "The Pingers",
  "The Pipeline Pirates",
  "The Pixel Pouncers",
  "The Pointers",
  "The Port 8080s",
  "The Preprocessors",
  "The Prime Factors",
  "The Private Keys",
  "The Programmers",
  "The Pseudo Coders",
  "The Public Statics",
  "The Quantum Leap",
  "The Query Queues",
  "The Quick Sorts",
  "The Race Conditions",
  "The RAM Robbers",
  "The Random Seeds",
  "The Readme Readers",
  "The Rebooters",
  "The Recursive Function",
  "The Redundant Arrays",
  "The Refactored",
  "The RegExps",
  "The Release Candidates",
  "The Repositories",
  "The Return 0s",
  "The Root Users",
  "The Routing Tables",
  "The Rubber Ducks",
  "The Rustaceans",
  "The Sandboxes",
  "The Scalability Seekers",
  "The Script Sprinters",
  "The Segment Faults",
  "The Semicolons",
  "The Server Sleuths",
  "The Shadow Devs",
  "The Ship-It Society",
  "The Singletons",
  "The Sockets",
  "The Software Surgeons",
  "The Spaghetti Squad",
  "The Stack Dumps",
  "The Standard In",
  "The Standard Out",
  "The Static Methods",
  "The Stored Procedures",
  "The String Theories",
  "The Subroutines",
  "The Sudoers",
  "The Switch Cases",
  "The Syntax Checkers",
  "The SysAdmins",
  "The System Crashes",
  "The Terminal Wizards",
  "The Test Dummies",
  "The Thread Safe",
  "The Throughputs",
  "The Time To Lives",
  "The Tokenizers",
  "The Trace Routes",
  "The Trojan Coders",
  "The Type Checkers",
  "The Undefineds",
  "The Unit Testers",
  "The Unix Unicorns",
  "The Unsigned Integers",
  "The User Agents",
  "The UTF-8 Ultimatum",
  "The Vaporware Vendors",
  "The Variables",
  "The Virtual Machines",
  "The Void Pointers",
  "The Web Crawlers",
  "The Web Sockets",
  "The Whiteboarders",
  "The Wildcards",
  "The Wireframes",
  "The Zero Days",
  "The Zero Indexed",
  "The Zombie Chasers",
  "Three Men And A Server",
  "Throughput Thrillers",
  "Thumb Drive Thugs",
  "Tick Tock CPU Clock",
  "Time Out Terror",
  "Tiny Code Titans",
  "To Boolean Or Not To Boolean",
  "Too Cool For School (Code)",
  "Total Meltdown",
  "Touch Grass Later",
  "Trial And Error",
  "True That Boolean",
  "Try Catch Finally Done",
  "Two Factor Authenticated",
  "Two Pointers In The Bush",
  "Type Inference Infiltrators",
  "Typo Typists",
  "Ultimate Algorithms",
  "Uncaught Promise",
  "Under The Hood",
  "Unexpected Token",
  "Unintended Feature",
  "Universal Serial Bus",
  "Unreachable Code",
  "Untracked Changes",
  "Up All Night To Get Lucky (With Code)",
  "User Friendly (Not)",
  "Variable Name 'x'",
  "Version 1.0.0-beta.99",
  "Vim Escapers Anonymous",
  "Virtual Reality Check",
  "Virus Hunters",
  "Void Star Sorcery",
  "Waiting For Server Response",
  "We Are Root",
  "We Break Everything",
  "We Hack Therefore We Are",
  "Web3 Wanderers",
  "Weekend Warriors",
  "Wheel Reinventors",
  "When In Doubt Reboot",
  "Whitespace Matters",
  "Who Broke The Build?",
  "Wi-Fi Password Finders",
  "Wireframed And Dangerous",
  "World Wide Wanderers",
  "Worst Case Scenario",
  "Wrap It In A Div",
  "Wrecking Ball DevOps",
  "X marks the spot (Twitter)",
  "Y Combinator Hopefuls",
  "Yesterday's Hotfix",
  "Yield To None",
  "You Had Me At Hello World",
  "Zero Effort Max Output",
  "Zero Warning Zealots",
  "Zombified Coders"
] as const;

/**
 * Returns a random funny tech team name, ensuring it is different from currentName.
 */
export function getRandomTeamName(currentName?: string): string {
  if (HACKATHON_TEAM_NAMES.length === 0) return "Cyber Knights";
  if (HACKATHON_TEAM_NAMES.length === 1) return HACKATHON_TEAM_NAMES[0];

  let candidate: string;
  let attempts = 0;
  do {
    const idx = Math.floor(Math.random() * HACKATHON_TEAM_NAMES.length);
    candidate = HACKATHON_TEAM_NAMES[idx];
    attempts++;
  } while (candidate === currentName && attempts < 10);

  return candidate;
}

